/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2019-04-05")
public class NodeWithTrack implements org.apache.thrift.TBase<NodeWithTrack, NodeWithTrack._Fields>, java.io.Serializable, Cloneable, Comparable<NodeWithTrack> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("NodeWithTrack");

  private static final org.apache.thrift.protocol.TField NODE_INFO_FIELD_DESC = new org.apache.thrift.protocol.TField("nodeInfo", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField TRACK_INFO_FIELD_DESC = new org.apache.thrift.protocol.TField("trackInfo", org.apache.thrift.protocol.TType.LIST, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new NodeWithTrackStandardSchemeFactory());
    schemes.put(TupleScheme.class, new NodeWithTrackTupleSchemeFactory());
  }

  public NodeInfo nodeInfo; // required
  public List<String> trackInfo; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    NODE_INFO((short)1, "nodeInfo"),
    TRACK_INFO((short)2, "trackInfo");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // NODE_INFO
          return NODE_INFO;
        case 2: // TRACK_INFO
          return TRACK_INFO;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.NODE_INFO, new org.apache.thrift.meta_data.FieldMetaData("nodeInfo", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, NodeInfo.class)));
    tmpMap.put(_Fields.TRACK_INFO, new org.apache.thrift.meta_data.FieldMetaData("trackInfo", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(NodeWithTrack.class, metaDataMap);
  }

  public NodeWithTrack() {
  }

  public NodeWithTrack(
    NodeInfo nodeInfo,
    List<String> trackInfo)
  {
    this();
    this.nodeInfo = nodeInfo;
    this.trackInfo = trackInfo;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public NodeWithTrack(NodeWithTrack other) {
    if (other.isSetNodeInfo()) {
      this.nodeInfo = new NodeInfo(other.nodeInfo);
    }
    if (other.isSetTrackInfo()) {
      List<String> __this__trackInfo = new ArrayList<String>(other.trackInfo);
      this.trackInfo = __this__trackInfo;
    }
  }

  public NodeWithTrack deepCopy() {
    return new NodeWithTrack(this);
  }

  @Override
  public void clear() {
    this.nodeInfo = null;
    this.trackInfo = null;
  }

  public NodeInfo getNodeInfo() {
    return this.nodeInfo;
  }

  public NodeWithTrack setNodeInfo(NodeInfo nodeInfo) {
    this.nodeInfo = nodeInfo;
    return this;
  }

  public void unsetNodeInfo() {
    this.nodeInfo = null;
  }

  /** Returns true if field nodeInfo is set (has been assigned a value) and false otherwise */
  public boolean isSetNodeInfo() {
    return this.nodeInfo != null;
  }

  public void setNodeInfoIsSet(boolean value) {
    if (!value) {
      this.nodeInfo = null;
    }
  }

  public int getTrackInfoSize() {
    return (this.trackInfo == null) ? 0 : this.trackInfo.size();
  }

  public java.util.Iterator<String> getTrackInfoIterator() {
    return (this.trackInfo == null) ? null : this.trackInfo.iterator();
  }

  public void addToTrackInfo(String elem) {
    if (this.trackInfo == null) {
      this.trackInfo = new ArrayList<String>();
    }
    this.trackInfo.add(elem);
  }

  public List<String> getTrackInfo() {
    return this.trackInfo;
  }

  public NodeWithTrack setTrackInfo(List<String> trackInfo) {
    this.trackInfo = trackInfo;
    return this;
  }

  public void unsetTrackInfo() {
    this.trackInfo = null;
  }

  /** Returns true if field trackInfo is set (has been assigned a value) and false otherwise */
  public boolean isSetTrackInfo() {
    return this.trackInfo != null;
  }

  public void setTrackInfoIsSet(boolean value) {
    if (!value) {
      this.trackInfo = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case NODE_INFO:
      if (value == null) {
        unsetNodeInfo();
      } else {
        setNodeInfo((NodeInfo)value);
      }
      break;

    case TRACK_INFO:
      if (value == null) {
        unsetTrackInfo();
      } else {
        setTrackInfo((List<String>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case NODE_INFO:
      return getNodeInfo();

    case TRACK_INFO:
      return getTrackInfo();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case NODE_INFO:
      return isSetNodeInfo();
    case TRACK_INFO:
      return isSetTrackInfo();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof NodeWithTrack)
      return this.equals((NodeWithTrack)that);
    return false;
  }

  public boolean equals(NodeWithTrack that) {
    if (that == null)
      return false;

    boolean this_present_nodeInfo = true && this.isSetNodeInfo();
    boolean that_present_nodeInfo = true && that.isSetNodeInfo();
    if (this_present_nodeInfo || that_present_nodeInfo) {
      if (!(this_present_nodeInfo && that_present_nodeInfo))
        return false;
      if (!this.nodeInfo.equals(that.nodeInfo))
        return false;
    }

    boolean this_present_trackInfo = true && this.isSetTrackInfo();
    boolean that_present_trackInfo = true && that.isSetTrackInfo();
    if (this_present_trackInfo || that_present_trackInfo) {
      if (!(this_present_trackInfo && that_present_trackInfo))
        return false;
      if (!this.trackInfo.equals(that.trackInfo))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_nodeInfo = true && (isSetNodeInfo());
    list.add(present_nodeInfo);
    if (present_nodeInfo)
      list.add(nodeInfo);

    boolean present_trackInfo = true && (isSetTrackInfo());
    list.add(present_trackInfo);
    if (present_trackInfo)
      list.add(trackInfo);

    return list.hashCode();
  }

  @Override
  public int compareTo(NodeWithTrack other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetNodeInfo()).compareTo(other.isSetNodeInfo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNodeInfo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.nodeInfo, other.nodeInfo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTrackInfo()).compareTo(other.isSetTrackInfo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTrackInfo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.trackInfo, other.trackInfo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("NodeWithTrack(");
    boolean first = true;

    sb.append("nodeInfo:");
    if (this.nodeInfo == null) {
      sb.append("null");
    } else {
      sb.append(this.nodeInfo);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("trackInfo:");
    if (this.trackInfo == null) {
      sb.append("null");
    } else {
      sb.append(this.trackInfo);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (nodeInfo != null) {
      nodeInfo.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class NodeWithTrackStandardSchemeFactory implements SchemeFactory {
    public NodeWithTrackStandardScheme getScheme() {
      return new NodeWithTrackStandardScheme();
    }
  }

  private static class NodeWithTrackStandardScheme extends StandardScheme<NodeWithTrack> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, NodeWithTrack struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // NODE_INFO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.nodeInfo = new NodeInfo();
              struct.nodeInfo.read(iprot);
              struct.setNodeInfoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // TRACK_INFO
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.trackInfo = new ArrayList<String>(_list0.size);
                String _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = iprot.readString();
                  struct.trackInfo.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setTrackInfoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, NodeWithTrack struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.nodeInfo != null) {
        oprot.writeFieldBegin(NODE_INFO_FIELD_DESC);
        struct.nodeInfo.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.trackInfo != null) {
        oprot.writeFieldBegin(TRACK_INFO_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.trackInfo.size()));
          for (String _iter3 : struct.trackInfo)
          {
            oprot.writeString(_iter3);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class NodeWithTrackTupleSchemeFactory implements SchemeFactory {
    public NodeWithTrackTupleScheme getScheme() {
      return new NodeWithTrackTupleScheme();
    }
  }

  private static class NodeWithTrackTupleScheme extends TupleScheme<NodeWithTrack> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, NodeWithTrack struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetNodeInfo()) {
        optionals.set(0);
      }
      if (struct.isSetTrackInfo()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetNodeInfo()) {
        struct.nodeInfo.write(oprot);
      }
      if (struct.isSetTrackInfo()) {
        {
          oprot.writeI32(struct.trackInfo.size());
          for (String _iter4 : struct.trackInfo)
          {
            oprot.writeString(_iter4);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, NodeWithTrack struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.nodeInfo = new NodeInfo();
        struct.nodeInfo.read(iprot);
        struct.setNodeInfoIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.trackInfo = new ArrayList<String>(_list5.size);
          String _elem6;
          for (int _i7 = 0; _i7 < _list5.size; ++_i7)
          {
            _elem6 = iprot.readString();
            struct.trackInfo.add(_elem6);
          }
        }
        struct.setTrackInfoIsSet(true);
      }
    }
  }

}

